### ISSUE TITLE
bug: root typecheck fails without generated SolidStart output

### ISSUE THREAD

**Issue by Peyton-Spencer** [omniaura/omniclaw#423]
## Summary

`bunx tsc --noEmit` fails on `main` after the SolidStart web UI merge because `src/web/solid-handler.ts` statically imports a generated build artifact that does not exist in a fresh checkout.

## Reproduction

1. Check out `main` at `f19a036` (current `origin/main` as of 2026-03-25).
2. Install dependencies:

```bash
bun install
```

3. Run:

```bash
bunx tsc --noEmit
```

4. Observe the error:

```text
src/web/solid-handler.ts(43,18): error TS2307: Cannot find module '../../webui/.output/server/index.mjs' or its corresponding type declarations.
```

## Expected

`bunx tsc --noEmit` passes on a fresh checkout of `main` without requiring a prior `webui` build step.

## Actual

TypeScript fails immediately because `src/web/solid-handler.ts` imports `../../webui/.output/server/index.mjs`, but that generated output is absent in a clean repo state.

## Notes

- `bun run build` succeeds.
- `bun test` also passes (`1419` passing, `0` failing).
- This regression appears after PR #418 (`feat: SolidStart web UI — complete migration from Datastar SSE`).
- `src/web/solid-handler.ts:43` is doing a runtime-only import, but the current implementation makes it a compile-time typecheck dependency.

## Suggested Fix

Pick one of these and make it consistent:

1. Add a checked-in module declaration/stub so `tsc` can resolve the generated server entry.
2. Refactor the import path so TypeScript does not need the generated `.output` artifact present during normal repo typechecking.
3. Make the webui build an explicit prerequisite of the root typecheck and document/enforce that in scripts and CI.
