### ISSUE TITLE
typecheck: bunx tsc --noEmit fails on main in logger subscriber test

### ISSUE THREAD

**Issue by Peyton-Spencer** [omniaura/omniclaw#560]
# typecheck: `bunx tsc --noEmit` fails on main in logger subscriber test

## Summary

TypeScript is currently failing on `main`, but the failure has moved since #551 was filed.

## Reproduction

1. Sync and install:
   ```bash
   git fetch --all --prune
   bun install
   ```
2. Run:
   ```bash
   bunx tsc --noEmit
   ```

## Observed result

`tsc` reports:

```text
src/logger.test.ts(513,41): error TS2493: Tuple type '[]' of length '0' has no element at index '0'.
```

The failing assertion is in the `subscribeToLogs()` alias test and indexes into `subscriber.mock.calls[0]?.[0]`.

## Expected result

- `bunx tsc --noEmit` should pass on `main`

## Notes

- This supersedes the original reproduction in #551, which no longer fails in `src/whatsapp-auth.ts` / `src/whatsapp-auth.test.ts`
- Current main-branch typecheck is still red, so this remains a CI blocker even though the specific failure changed

**Comment by Peyton-Spencer** [comment]
**PM note (Apr 19):** Second of two P1 CI blockers on main. The fix should be straightforward — the test at `src/logger.test.ts:513` indexes into `subscriber.mock.calls[0]?.[0]` but TypeScript infers an empty tuple type for `mock.calls`. Likely just needs a type assertion or a guard to satisfy the compiler.

**Comment by Peyton-Spencer** [comment]
Verified Apr 23: `bunx tsc --noEmit` passes clean on current main (commit f29babb). The logger subscriber typecheck error is no longer present — likely fixed by one of the recent merges. Closing as resolved.

Tracking issue #583 has been updated to reflect this.
