### ISSUE TITLE
bug: fs module mock in group-queue.test.ts leaks into task-scheduler.test.ts

### ISSUE THREAD

**Issue by Peyton-Spencer** [omniaura/omniclaw#70]
## Problem

Running `bun test` produces 1 failure in `task-scheduler.test.ts`:

```
TypeError: fs.mkdtempSync is not a function
```

The test `buildHeartbeatPrompt > returns sensible default when no CLAUDE.md files exist` fails because `fs.mkdtempSync` and `fs.rmSync` are `undefined`.

## Root Cause

`group-queue.test.ts` (line 11) uses `mock.module('fs', ...)` to replace the `fs` module with a partial mock that only includes `mkdirSync`, `writeFileSync`, and `renameSync`:

```ts
mockModule.module('fs', () => ({
  default: {
    mkdirSync: mock(),
    writeFileSync: mock(),
    renameSync: mock(),
  },
}));
```

When Bun runs tests in the same process, this mock leaks into other test files. `task-scheduler.test.ts` then gets the mocked `fs` module missing `mkdtempSync` and `rmSync`.

## Reproduction

```bash
bun test  # 1 fail - task-scheduler.test.ts
bun test src/task-scheduler.test.ts  # 0 fail - passes in isolation
```

## Suggested Fix

Option A: Scope the mock properly — use `beforeEach`/`afterEach` to restore the original `fs` module in `group-queue.test.ts`.

Option B: Include all `fs` methods used across tests in the mock, or spread the real `fs` and override only the needed methods:

```ts
import realFs from 'fs';

mockModule.module('fs', () => ({
  default: {
    ...realFs,
    mkdirSync: mock(),
    writeFileSync: mock(),
    renameSync: mock(),
  },
}));
```

Option C: Use Bun's `--preload` or file-level isolation flags if available.

## Environment

- Bun 1.3.9
- Tests: 422 pass, 1 fail across 17 files

Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>
